name: ziggurat_utils
description: Various utilities for use with the [ziggurat]([URL](https://pub.dev/packages/ziggurat)) package.
version: 1.0.1
repository: https://github.com/chrisnorman7/ziggurat_utils

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  vault: vault
  data2json: data2json
dependencies:
  args: ^2.2.0
  encrypt: ^5.0.1
  ziggurat: ^0.10.1
  ziggurat_sounds: ^0.0.0
